# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.4
  - 2.7

env:
  matrix:
    - DJANGO=1.7.9 CMS=3.0.14
    - DJANGO=1.7.9 CMS=3.1
    - DJANGO=1.8.3 CMS=3.0.14
    - DJANGO=1.8.3 CMS=3.1

install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO
  - pip install -q django-cms==$CMS
  - python setup.py -q install

script: 
  - coverage run $(which djangocms-helper) cmsplugin_iconlist test --cms

after_success: coveralls
