# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.4

env:
  - DJANGO=1.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO
  - python setup.py -q install

script: 
  - python fake_test.py
