# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.4
  - 3.5
  - 2.7

env:
  matrix:
    - DJANGO=1.8.12 CMS=3.0.16
    - DJANGO=1.8.12 CMS=3.1.16
    - DJANGO=1.8.12 CMS=3.2.3
    - DJANGO=1.9.5 CMS=3.0.16
    - DJANGO=1.9.5 CMS=3.1.16
    - DJANGO=1.9.5 CMS=3.2.3

install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO
  - pip install -q django-cms==$CMS
  - python setup.py -q install

script: 
  - coverage run $(which djangocms-helper) cmsplugin_iconlist test --cms

after_success: coveralls
