# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.4

env:
  - DJANGO=1.7.7

install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO
  - python setup.py -q install

script: 
  - $(which djangocms-helper) cmsplugin_iconlist test --cms

after_success: coveralls
